spring:
  datasource:
    # datasource configuration example.
    # It may also work with RDBMSs other than MySQL, but not tested.
    url: jdbc:mysql://localhost:3306/wiki_dev  #?rewriteBatchedStatements=true
    username: root
    password: test1234
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true  # highly recommended due to performance reasons
  jdbc:
    batch_size: 1000
    show-sql: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      order_inserts: true
      order_updates: true
      jdbc:
        batch_size: 100
        show-sql: true
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 100

yawiki:
  default-permission:
    doInitialize: true
    create: 0
    read: 0
    update: 0
    delete: 0
    manage: 3
  jwt:
    lifespan: 1800
#  cors:
#    allowed-origins: *
#    allowed-methods: *

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc: DEBUG
