spring:
#  profiles:
#    active: local
  datasource:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true  # highly recommended due to performance reasons
  jdbc:
    batch_size: 100
    show-sql: false
